hash-format = "sha256"

[[files]]
file = ".directory"
hash = "ac41f8f6e3fcc21747aae54409ead6484a2df8b1d013e2ebc560ccc968a677d2"

[[files]]
file = "mods/actually-harvest.pw.toml"
hash = "246669da59267111727608f860abc2232705a5bd9cc00e53d8a64d36d849ce22"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "1e5b00de09f3382cb89564dca455b0d547855c09d8d28d2e98e47d95fabcaeff"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "5b332b628f2bbb11afdc82f4a9d27ca3afde5ad2d21c590af5c7a080c2aa9dfa"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "71dc04da11ad8f4a5d88db5505132a654ce033f05dc2fa4bb7aa28a42762086f"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "30d759179cc7ebb5f798ed79d521ad01b11e5831c0f83d6bd98518931c03b869"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "0b5feeae74fe992084ec5cb12eab3404ddd5054e85c9006f7ba4d65f209de13f"
metafile = true

[[files]]
file = "mods/bountiful.pw.toml"
hash = "88d4b6472c19d1a2afe1b287c052d17559ac96603b8bbbcf82ad7a9068d953e6"
metafile = true

[[files]]
file = "mods/build-guide.pw.toml"
hash = "6b35a0220be7bcf242e1c56c82371d237da641e7436f5a2893a2c53e60fd46cb"
metafile = true

[[files]]
file = "mods/building-wands.pw.toml"
hash = "d250a791b3ec9538036276fde244293c9c6d1854d6073d13f731f0fe36c73ff7"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "5ba003768a235ab0d811218191166f9aefa4c9a2509341fbba1efd80e18d3676"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "fed6f66373bb06b6ff552c97cd9cdbdf78ec429320252619e563f9a4fb65feb9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "b4fdf52d53ab71bf73282c5168e9526b6024740d82388d604d6947394e3c7f7f"
metafile = true

[[files]]
file = "mods/connectiblechains.pw.toml"
hash = "307bbd346d813c85bf956269caa56a017a445397c2bc18ca3b64a50f5801741d"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "1eb94c241ed2d519e5bde972b0a7966041684d75cbfc724c3ec55227830316a1"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "5944ed5a779d142aea9ccd8c466a20fa3d9233a29f2be1e5ae54fc15f5edd57e"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "121a04de1d3ab857994236f5efc79c37a2275714d2f3ec9424d3b7e9721b36ed"
metafile = true

[[files]]
file = "mods/draggable-lists.pw.toml"
hash = "bfe939f563e561df6410a82e9f36ec3793634e470c9b729088072ff8824018ac"
metafile = true

[[files]]
file = "mods/dramatic-doors.pw.toml"
hash = "8143c63aa2e53fd78ea83eddba9cfaa4c036141aae6604eb01d8f82dc5d03c99"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "a3a5120e8cd41a3ac7d2283714525c9c67b93a8718583c90b604770b2b379059"
metafile = true

[[files]]
file = "mods/effective.pw.toml"
hash = "c882f6e32cb2c201f1ad3b4dfb6f537517af7955792fa9418de3afe83ebd9e1e"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "fec1ffa03b4d62e47be25512840490844fc383cf82d2ad35345b2f87a21e8228"
metafile = true

[[files]]
file = "mods/enchancement.pw.toml"
hash = "54ed85b42559773c1d59f774b7d1e17938232b97432b20469ead70d69673b6ab"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "b13f84a7fad7d6e21cef513a9c8f8206e55f0b342b4030df540e3126ad5abb2a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "58a487d9e3761d18f529cf141c873ea054e8f26c5e90601a3c8cf60fc723b22d"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "605c081279d8e4e5c98e6a50304867214185d8b8f14434b71d388a20f4ad7d5d"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "6a16810d228d5f6d8d91af1397340f89fed4a0c12cc63ff60b52b9d7cb7c72df"
metafile = true

[[files]]
file = "mods/extractinator.pw.toml"
hash = "fe3fdbd01b83896d96c3f0e8dedc921c45fb034a94fc087b106dd6607c054dc0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fairy-lights-fabric.pw.toml"
hash = "1c3c3cfd3c5739c289262319eddc8994d55ddd984d96651fbd1ecbdac67278ff"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "fff1e00559f13c092b17fa83804279cf70191d7a99a4a98a4eb6bb30ac9a78db"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "adea09f1e1b05da68cf7407992a9391b15985acf5465a888e54ae076dbd543ab"
metafile = true

[[files]]
file = "mods/fossils-and-archeology-revival.pw.toml"
hash = "5f4a30ef1cffa796ceaf83973bfd5aaee59f412149d0b9b83b5168fd428a11c0"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "b0866b0a27163b903b4d4d0d21f5959c3e481bce03653afd0ce9c6a7e1fbf299"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "21d2df923fa369d69a40d69f6466153146bf403367430eaeb2569c1554857df8"
metafile = true

[[files]]
file = "mods/held-item-info.pw.toml"
hash = "b085a13f441287ee000f3d17b49755741ed738a2a296fe349c79c01ed9d81350"
metafile = true

[[files]]
file = "mods/horseman.pw.toml"
hash = "75be56cc068db54ef72d3413cf11a4bea272beed606db8a3ee4c305cbe598d95"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "67b0b2bd471fc2393c7c8e95cae5ae6031e621d11f5e253c07a4427857f1a2bd"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/infinitybuttons.pw.toml"
hash = "f06d859796e84c8ecbdbbabd07c988d8c9b94f4c4ee3ab7dcce9400e4d073a62"
metafile = true

[[files]]
file = "mods/interactic.pw.toml"
hash = "35e1f90f1d79f773a7fb1f7dde9050e40087107d77ced4431c40124a87544c78"
metafile = true

[[files]]
file = "mods/inventory-management.pw.toml"
hash = "5f74332db22a2eda4c05a7469cf57af07438ccb3fbb016b1ba9131b7164e7a1a"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
hash = "b28167f09bbcaca3fee27d748191ed19ce37b9382bb4ae693a20f415f80ed305"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/kambrik.pw.toml"
hash = "a06e2f058ccc09999d2437517969b248bc7008ea9e990996b11d7458253784f7"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "c8766f2ad1ae837ec4021167fc08bb9604c036d0fd12d7fc63bb407eaecb080e"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8508e46b7e272d79dc6b3cc0149f9fd132c701369bcb2abb5c35da3ed92b27fb"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "bc91fa90e9f26f3ff3690c1a508647a162cd63dc36d815b8af0d6f5e01e5ecbf"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "0d438cc5a467aae6a9aa439a4547f990dfbaa4dc4e7bf5dbabf6d6e839411e83"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "200d34b575b506ab0503f7856cdcd4cc38030c27e0749e36f6bbe62cbeb16cec"
metafile = true

[[files]]
file = "mods/more-hitboxes.pw.toml"
hash = "6df5965c9c14d14b1cd89c8c2f1ca162a9742cab21dbb48d38f1e21daca1ba6e"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "dbb344ad3e49c36d167fa05b6c5f674794306b1727220e8720d767264aee497f"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/niftycarts.pw.toml"
hash = "85403dfbcff240580a8630397c8a2da2c9a006fc3e4236948983520121c4620d"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
hash = "da9ac20bdc1caa50ebec291429638780924e8a5060ec39abe085c7e6182b3a6f"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "e94cfc8b72a467d63c5d7593a433edaf698a3792e0c9b95274751ba6d8435288"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "89ed99a0798a5e1300434359762c968536593279493f68b321a565fb1343f75c"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "071ce6bcd5614ceb07718b646f1012faf9c449eb8e56c0b740929a9efada593c"
metafile = true

[[files]]
file = "mods/numismatic-bounties.pw.toml"
hash = "7e064eaaa283817c1f32d1ee321ade053fc18336e9afd5b967c96965c02e5f58"
metafile = true

[[files]]
file = "mods/numismatic-overhaul.pw.toml"
hash = "d86eb8f7bd1df802d4b7c99c96b1098bc530e4bcb7f75f7eee0232ac119e85e6"
metafile = true

[[files]]
file = "mods/omnicut-better-wood-stone-cutter.pw.toml"
hash = "fc81805cbce149290a3f5adbb8bca08806d864e6fb6efba7c6d9e02a5890fa7f"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "3f8f31eed84a4a29618cf04e300ea02ace03095ff4e8c4c23ec92f09849ed1f0"
metafile = true

[[files]]
file = "mods/open-simple-frames.pw.toml"
hash = "d8b7084e1c8e42b6fce3c648b12b5a4a1595771670cb6372a9ff5f2092958c2c"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "df4c4fe3aff1792aa7d19d097d5d1bc0c6e958e6e4ee32dbf148ecac62e1274d"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "887a35d1f5d600b8ad165d3386614a789e077ca5895d4c7cc20e1aa2e2a716c5"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "2a0fca7186e870cd4134a7d27c42ab637c97c86a6459a7fcfb72d3e1cccfe966"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
hash = "5beb6ef32d80ab0550baad15f1fd78f2c6168fcce4a18e14e23c47a1cc8ed099"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8293786ca23e23e7dd04d60d666f34145a00229a5959f7a1962995654cacdf1f"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "b9cc93ef79f4acef43610a310d09d83f3bcee7288eea366d361fcc7181168fd3"
metafile = true

[[files]]
file = "mods/radiant-gear.pw.toml"
hash = "7eae70ce9d8985f5253b576c74c6f1c341cf2e3292df26a47e47801df5d6e687"
metafile = true

[[files]]
file = "mods/reacharound.pw.toml"
hash = "c08dcea37c03dcb5cfad9d3d14f5e885995cf9bb74975244781e1354c937afa7"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
hash = "767f1d29cf465dc38d5ef9a93b2a9d4c54daad8c82535d525070efd97f504ad9"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "77a658a9d9cec5037136b95c42d1dff26dbf4010f17ecb2116bebf69178a03ba"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "3f9e020fb15e1c2ede36d50b40c72d536f6de3f817bd703d26805a747175c8bc"
metafile = true

[[files]]
file = "mods/roadarchitect-encounters.pw.toml"
hash = "c4a2615f41c0c692c13713aef6af3133bf2631b45437bf4c8f3e20b70ae094c3"
metafile = true

[[files]]
file = "mods/roadarchitect.pw.toml"
hash = "1106c1203ea71a55d578e6ff93b23f013655887d0d09c04b1b898ab28bd243d3"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "83164a6af3923e28cadf9d404f059bf74aa4f0842fc1ca0f6e7cf1e686044875"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "058f62395b41a3b18121bcd961320cc8fd8460a34a5ccb4f07552e42ff19df4a"
metafile = true

[[files]]
file = "mods/simple-belt-lanterns.pw.toml"
hash = "15a808dcac3a064074b22bde2ddf939883cb754cfce97abe5628b75078b15bdc"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8ad07191dfdea31249b4416a390c1cdf1d4ff1938cf9f8a617f98f7a08c5356c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
hash = "0238d3e484f1829aaabb3b2482e528e192f3124fad89d81f43d7b60406e17d71"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
hash = "6e5a8f947f77a0a9cf18347edd01a08fc725c2ecaa10cf61e6b429a54e50a463"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "5cd3420078c7c24bf7414c7243a69b2d2a21c3c5e29150444697b11a001c44d8"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
hash = "116f803a2b3c68c5b0b7bfbad1fd9072ed3df78a1dcdfa8c48f70e5ef450f620"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "3135bb6ec401e951d248de79dbdf40608e362e64b89fe9e7d2e74399f3b49375"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "b3ae602303fd717bff2344bfb89aa427e2b4a1ab5fffdcc25183b22102c492df"
metafile = true

[[files]]
file = "mods/terralith-biome-saplings.pw.toml"
hash = "df9d95f41bc7d6ca92c09d086e9b756bec261f0bb011e9a5de9e9bd98f1d6c59"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "f26fb3886f4c53b3284264cacfebb4bfe68a189205363e8e406896c847c1e0ea"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "ddd37f4bf3fa0276351911e72b412ebb4de271ce802c1c7b89df0bf321417eb0"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "72c0e1d4d8eb05e6c82c8959885ee5f08b8c7ede63b438e22a7422246679cc46"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "df71b5d7427e9a508e9f298b5cdec84aa8c4fcb584beb0d16d86efb9d47b3bcd"
metafile = true

[[files]]
file = "mods/treechop.pw.toml"
hash = "d4973af17081ec2f1d5aabad778331459612fc95617cda5fbcafa79ea9384c43"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ffdb79f5bc29f990e5889f5d159a043c7046b8cd8d79f17f54b44d7ccc2b242a"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "3850ba97b0333e8a93577e2d6352659e63bdefa295c704b18431ae233b6040e8"
metafile = true

[[files]]
file = "mods/vanilla-backport-terralith-bwg-compat.pw.toml"
hash = "a449bdeadcba1999e3207476595c35e61c801efc5479019b6a1c364c86f241a3"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
hash = "e17c2c575f2db23bb4e6cb7035093ec67f0c2189e7e3026075794579c6a05fd4"
metafile = true

[[files]]
file = "mods/wakes.pw.toml"
hash = "9cfd88046df56c5df4c8fceed56d65e434e230025b46d85a358a08bfa6381e4a"
metafile = true

[[files]]
file = "mods/wi-zoom.pw.toml"
hash = "44d8c335a317321656239b2dd2a90ade818d71f6f3b2de46467feb5442677c52"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "fd725a2383164ee2866a41635b0a8baf4cc1506d33df1ce1cc1455ab98a32e01"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "7598f0435251f845fdf85c8ed2ac612b2d0404e0ee73a1fcdebaf4eb6c95296d"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true

[[files]]
file = "mods/zipline.pw.toml"
hash = "ba107fdc54fb208245d2770ec74dd5776db5942000afee4b45169b67e14d8444"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.pw.toml"
hash = "66fd4a47f4eb3fc7b0e487b0fafc998f009e889188bcc5a609d04c2ab97e369f"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "resourcepacks/fancyfast-bushy-leaves.pw.toml"
hash = "2a61421eeb20758224c372b28640103661c434f2ecbf4c15153f0a655a548591"
metafile = true

[[files]]
file = "resourcepacks/fine-armoury.pw.toml"
hash = "84eb4bf56150f20451bd3687959a41ff06b52e3b7335e7f2c50d8a7c418876f5"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-creepers.pw.toml"
hash = "7913ccc031786220b0d2226389d2f034369183572e7071e5d7612b442359f130"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-details.pw.toml"
hash = "870f127871c2347f9c64006de03906d11655a5799af2a9862a7529bee8b8de1a"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-emissive.pw.toml"
hash = "36f1f87cc258740fa9929f90a784ed91aaf211f75a3973b067d01ec4c12ce926"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-ghasts-galore.pw.toml"
hash = "172fd7fb75f40d6d2f3a967a34a3e3c2627deb9851368eb077c02e863d5b0566"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-objects.pw.toml"
hash = "4a2a1d4fb13506f5011fa74e9ca441e766b6727cff54e5672a2cb945b6d3f17c"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-spiders.pw.toml"
hash = "3603263cecdbedd8d3e94aec2e6c99947b559e760c3819a44ef0e72d71298d8c"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "42b8a59616b3ed15a02e55466dff7ab400d481a8730949ce0168a927b71b91fb"
metafile = true

[[files]]
file = "resourcepacks/fusion-block-transitions.pw.toml"
hash = "e5f49f7a3b49f7a03f667c5c5ca43826e7abbfcc0a9fe2499af89b461fac0819"
metafile = true

[[files]]
file = "resourcepacks/fusion-connected-blocks.pw.toml"
hash = "0e27eea95511f0914b8db1e75cfde84ca748251bc5d24c42dd9af38abd77afdc"
metafile = true

[[files]]
file = "resourcepacks/fusion-connected-glass.pw.toml"
hash = "cc4c03200baa367d40720320336b692e6c4fe71edbea890e27210bb2cc42408c"
metafile = true

[[files]]
file = "resourcepacks/new-spawn-eggs-vanilla-backport-compat.pw.toml"
hash = "35dc44f5ab4f9062be9306c7be4818658271b8bf5bc98759ddf50b47f93df698"
metafile = true

[[files]]
file = "resourcepacks/simple-grass-flowers.pw.toml"
hash = "bc4dcbd6b77adb2180049d63ed4a8981553f06dbf3e32080022ffd87dd1fb09b"
metafile = true

[[files]]
file = "resourcepacks/simple-lower-grass-sides.pw.toml"
hash = "95df280d41e71aa4a6db43b9f56196a716f238660b0135c05155980e36778304"
metafile = true

[[files]]
file = "resourcepacks/sparkles.pw.toml"
hash = "4d1f80d4aea6f81427b67313796afa14e4319d6284ea512169243a74f7c74ba7"
metafile = true

[[files]]
file = "resourcepacks/tras-fresh-player.pw.toml"
hash = "a2281fdf9db2f273f97a5c17d0179e8e104372ba0539ff50145e9fba28c3dc69"
metafile = true

[[files]]
file = "resourcepacks/vanilla-backport-x-fresh-animations.pw.toml"
hash = "92582b5a76e548fa4d64f72b569b5c7bf06026c3642526d35c9f1102e73f4c3a"
metafile = true
