name = "Pao Jurassico"
author = "koiitulip"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19ace0a14a1fb0d07edf2dc6d7f04ae8b125ce94926feb6aefac9c137c7145ad"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
