name = "Pao Jurassico"
author = "koiitulip"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6f00fc5acc189eeebbf0899d740cd8fb4bee2387141c5b55356ae6478d0fb4b"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
