name = "Pao Jurassico"
author = "koiitulip"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b434aa1b25af60c129ea25b9e462736ec9e7d7a03f9c818edd5755dcef7ec32"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
