name = "Pao Jurassico"
author = "koiitulip"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d413ae8d1bebb77ed5ac9e4e2865640dcd676b84053a66675c7d811ca1090f43"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
