name = "Pao Jurassico"
author = "koiitulip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "807e8c6de29ae905438dd1cf01a47f4fb0874b89ff3e2d53bef4a8e47986873a"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
