name = "Pao Jurassico"
author = "koiitulip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fc898e039ebdc036cf1166da8b7a7d7276a416dca5773fc8b556367366d418e"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
